optim: adam
max_epoch: 100
batch_type: folded
sort_batch: descending
batch_size: 4
valid_batch_size: 4
iterator_type: sequence
chunk_length: 32000
# exclude keys "enroll_ref", "enroll_ref1", "enroll_ref2", ...
# from the length consistency check in ChunkIterFactory
chunk_excluded_key_prefixes:
  - "enroll_ref"
  - "utt2category"
# - "speech_ref"
n_mix:
  - 5
num_workers: 8
optim_conf:
  lr: 1.0e-04
  eps: 1.0e-08
  weight_decay: 0
unused_parameters: true
patience: 10
accum_grad: 1
grad_clip: 5.0
val_scheduler_criterion:
  - valid
  - loss
best_model_criterion:
  - - valid
    - snr
    - max
  - - valid
    - loss
    - min
keep_nbest_models: 5
scheduler: warmupsteplr
scheduler_conf:
  # for WarmupLR
  warmup_steps: 5000
  # for StepLR
  steps_per_epoch: 5000
  step_size: 2
  gamma: 0.98

model_conf:
  num_spk: 5
  share_encoder: true
  task: enh
  normalization: true

train_spk2enroll: data/tr_min_8k/spk2enroll.json
enroll_segment: 32000
load_spk_embedding: false
load_all_speakers: true

encoder: conv
encoder_conf:
  channel: 64
  kernel_size: 16
  stride: 8
decoder: conv
decoder_conf:
  channel: 64
  kernel_size: 16
  stride: 8
extractor: dptnet_eda
extractor_conf:
  num_spk: 5
  layer: 6
  rnn_type: lstm
  bidirectional: True # this is for the inter-block rnn
  unit: 128
  segment_size: 100
  att_heads: 4
  dropout: 0
  activation: relu
  norm_type: gLN
  nonlinear: prelu
  triple_path: false
  i_eda_layer: 3
  i_adapt_layer: null
  adapt_layer_type: attn
  adapt_enroll_dim: 64

# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions:
  # The first criterion
  - name: si_snr
    conf:
      eps: 1.0e-7
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: true

use_wandb: false
wandb_project: use_preliminary_wsj
wandb_name: NoisyRev2_DPTNet_Sep_EDA4thLayer_5mix_SISNR+1BCELoss_woAMP_StepLR_lr1e-4_steplr5000steps

init_param:
  - ../enh_tse1/exp/enh_enh_dptnet_eda4thlayer_2-5mix_1bce_raw/175epoch.pth
