optim: adam
max_epoch: 100
batch_type: folded
batch_size: 32
iterator_type: chunk
chunk_length: 32000
# exclude keys "enroll_ref", "enroll_ref1", "enroll_ref2", ...
# from the length consistency check in ChunkIterFactory
chunk_excluded_key_prefixes:
- "enroll_ref"
num_workers: 8
optim_conf:
    lr: 1.0e-04
    eps: 1.0e-08
    weight_decay: 0
unused_parameters: true
patience: 10
accum_grad: 1
grad_clip: 5.0
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.7
    patience: 3

model_conf:
    share_encoder: true

train_spk2enroll: data/train-100/spk2enroll.json
enroll_segment: 32000
load_spk_embedding: false
load_all_speakers: false

encoder: stft
encoder_conf:
    n_fft: 512
    hop_length: 128
decoder: stft
decoder_conf:
    n_fft: 512
    hop_length: 128
extractor: asenet
extractor_conf:
    separator_hidden_dim: 512
    separator_num_layers: 1
    maskestimator_hidden_dim: 512
    maskestimator_num_layers: 2
    attention_dim: 200
    dropout_p: 0.3

# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions:
  # The first criterion
  - name: snr
    conf:
      eps: 1.0e-7
    wrapper: fixed_order
    wrapper_conf:
      weight: 1.0

use_wandb: true
wandb_project: universal_speech_enhancement
wandb_name: asenet_tse_softmaxTemp2_2outputs_bs32
