optim: adam
max_epoch: 200
batch_type: folded
sort_batch: descending
batch_size: 4
valid_batch_size: 4
iterator_type: sequence
chunk_length: 32000
# exclude keys "enroll_ref", "enroll_ref1", "enroll_ref2", ...
# from the length consistency check in ChunkIterFactory
chunk_excluded_key_prefixes:
- "enroll_ref"
- "utt2category"
# - "speech_ref"
n_mix:
- 2
num_workers: 8
optim_conf:
    lr: 4.0e-04
    eps: 1.0e-04
    weight_decay: 0
unused_parameters: true
patience: 10
accum_grad: 1
grad_clip: 5.0
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 10
scheduler: warmupreducelr
scheduler_conf:
   # for WarmupLR
   warmup_steps: 10000
   # for StepLR
   factor: 0.7
   patience: 3

model_conf:
    num_spk: 5
    share_encoder: true
    task: enh
    normalization: true

train_spk2enroll: data/tr_min_8k/spk2enroll.json
enroll_segment: 32000
load_spk_embedding: false
load_all_speakers: true

encoder: conv
encoder_conf:
    channel: 64
    kernel_size: 16
    stride: 8
decoder: conv
decoder_conf:
    channel: 64
    kernel_size: 16
    stride: 8
extractor: dptnet_eda
extractor_conf:
    num_spk: 5
    layer: 6
    rnn_type: lstm
    bidirectional: True  # this is for the inter-block rnn
    unit: 128
    segment_size: 100
    att_heads: 4
    dropout: 0
    activation: relu
    norm_type: gLN
    nonlinear: prelu
    triple_path: false
    i_eda_layer: 3
    i_adapt_layer: null
    adapt_layer_type: attn
    adapt_enroll_dim: 64

# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions:
  # The first criterion
  - name: snr
    conf:
      eps: 1.0e-4
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: true
  - name: mr_l1_tfd
    conf:
      eps: 1.0e-4
      scale_invariant: false
      mean_or_sum: mean
    wrapper: pit
    wrapper_conf:
      weight: 10.0
      independent_perm: false
  - name: si_snr
    conf:
      eps: 1.0e-4
    wrapper: pit
    wrapper_conf:
      weight: 0
      independent_perm: false

use_amp: true
use_wandb: true
wandb_project: use_preliminary_wsj
wandb_name: DPTNet_Sep_EDA4thLayer_2mix_SNR+MRLoss+1BCELoss_AMPfloat16_ReduceLR